###
POST http://localhost:8000/historia HTTP/1.1
Content-Type: application/json

{
    "title": "EL APORTE DE LA ARQUEOLOGIA"
}

###

GET http://localhost:8000/historia HTTP/1.1

###
GET http://localhost:8000/historia/6287d200720c47b2f24fadc8 HTTP/1.1


###
POST http://localhost:8000/category HTTP/1.1
Content-Type: application/json

{
    "title": "Musica"
}

###
GET http://localhost:8000/category HTTP/1.1


###
POST http://localhost:8000/subcategory HTTP/1.1
Content-Type: application/json

{
    "title": "Subcategoria de Musica",
    "category": "Musica"
}

###
GET http://localhost:8000/subcategory HTTP/1.1



###
POST http://localhost:8000/articles HTTP/1.1
Content-Type: application/json

{
    "subcategory": "Subcategoria de Musica",
    "category": "Musica",
    "text": "Este es el texto",
    "images": "Esto es una imagen"
}

###
GET http://localhost:8000/articles HTTP/1.1