###
POST http://localhost:8000/historia HTTP/1.1
Content-Type: application/json

{
    "title": "EL APORTE DE LA ARQUEOLOGIA"
}

###

GET http://localhost:8000/historia HTTP/1.1

###
GET http://localhost:8000/historia/6287d200720c47b2f24fadc8 HTTP/1.1


###
POST http://localhost:8000/category HTTP/1.1
Content-Type: application/json

{
    "title": "Musica"
}

###
GET http://localhost:8000/category HTTP/1.1


###
POST http://localhost:8000/subcategory HTTP/1.1
Content-Type: application/json

{
    "title": "Subcategoria de Musica",
    "category": "Musica",
    "secondSubcategory": "Musisca" 
}

###
GET http://localhost:8000/subcategory HTTP/1.1

###
POST http://localhost:8000/secondsubcategory HTTP/1.1
Content-Type: application/json

{
    "title": "Segunda Subcategoria de Musica",
    "category": "Musica",
    "subcategory": "Musisca" 
}

###
GET http://localhost:8000/secondsubcategory HTTP/1.1


###
POST http://localhost:8000/articles HTTP/1.1
Content-Type: application/json

{
    "subcategory": "Subcategoria de Musica",
    "category": "Musica",
    "secondsubcategory": "Second Subcategoria de Musica",
    "title": "title de musica",
    "text": {
        "title": "primer titulo",
        "paragraph": "primer parrafo"
    },
    "images": "Esto es una imagen"
}

###
GET http://localhost:8000/articles/634345e228bf228179441c6d HTTP/1.1